from pydantic import BaseModel, Field
from typing import Optional, Literal

class ProjectCreateRequest(BaseModel):
    id: str  # We accept the ID generated by the frontend
    title: str
    created_at: int

class ProjectUpdateRequest(BaseModel):
    title: str
    
class ProjectResponse(BaseModel):
    id: str
    title: str
    root_path: str

class AssetResponse(BaseModel):
    id: str
    hash: str
    name: str
    type: Literal["video", "image", "audio", "mask", "effect"]
    src: str
    thumbnail: Optional[str] = None
    duration: Optional[float] = None
    created_at: int = Field(..., alias="createdAt")
    
    class Config:
        populate_by_name = True
