import type { RefObject } from "react";
import { styled } from "@mui/material/styles";
import { useTimelineMarquee } from "../hooks/useTimelineMarquee";

// Geometry changes on every pointer move, so it goes through `style`; the
// static look is hoisted here rather than regenerated by `sx` each frame.
const MarqueeBox = styled("div")({
  position: "absolute",
  border: "1px solid rgba(77, 171, 245, 0.9)",
  backgroundColor: "rgba(77, 171, 245, 0.12)",
  pointerEvents: "none",
  // Above clips (selected 10, snap line 25), below the ruler (40), playhead
  // (42) and sticky track headers (60).
  zIndex: 30,
});

interface TimelineMarqueeProps {
  scrollContainerRef: RefObject<HTMLDivElement | null>;
  onActivate?: () => void;
}

export function TimelineMarquee({
  scrollContainerRef,
  onActivate,
}: TimelineMarqueeProps) {
  const rect = useTimelineMarquee(scrollContainerRef, onActivate);
  if (!rect) return null;
  return (
    <MarqueeBox
      data-testid="timeline-marquee"
      style={{
        left: rect.left,
        top: rect.top,
        width: rect.width,
        height: rect.height,
      }}
    />
  );
}
