import { CRTFilter } from "pixi-filters";
import type { TransformationDefinition } from "../types";
import { filterHandler } from "../filterHandler";

export const crtFilterDefinition: TransformationDefinition = {
  type: "filter",
  compatibleClips: "visual",
  filterName: "CRTFilter",
  FilterClass: CRTFilter,
  label: "CRT Effect",
  handler: filterHandler,
  uiConfig: {
    groups: [
      {
        id: "crt_screen",
        title: "Screen",
        columns: 1,
        controls: [
          {
            type: "slider",
            label: "Curvature",
            name: "curvature",
            defaultValue: 1,
            min: 0,
            max: 10,
            step: 0.1,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Vignette",
            name: "vignetting",
            defaultValue: 0.3,
            min: 0,
            max: 1,
            step: 0.01,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Vignette Alpha",
            name: "vignettingAlpha",
            defaultValue: 1,
            min: 0,
            max: 1,
            step: 0.01,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Vignette Blur",
            name: "vignettingBlur",
            defaultValue: 0.3,
            min: 0,
            max: 1,
            step: 0.01,
            supportsSpline: true,
          },
        ],
      },
      {
        id: "crt_scanlines",
        title: "Scanlines",
        columns: 1,
        controls: [
          {
            type: "slider",
            label: "Line Width",
            name: "lineWidth",
            defaultValue: 1,
            min: 0,
            max: 10,
            step: 0.1,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Line Contrast",
            name: "lineContrast",
            defaultValue: 0.25,
            min: 0,
            max: 1,
            step: 0.01,
            supportsSpline: true,
          },
          {
            type: "link",
            label: "Vertical Lines",
            name: "verticalLine",
            defaultValue: false,
          },
        ],
      },
      {
        id: "crt_noise",
        title: "Noise",
        columns: 1,
        controls: [
          {
            type: "slider",
            label: "Noise",
            name: "noise",
            defaultValue: 0.3,
            min: 0,
            max: 1,
            step: 0.01,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Noise Size",
            name: "noiseSize",
            defaultValue: 1,
            min: 0,
            max: 10,
            step: 1,
            supportsSpline: true,
          },
          {
            type: "number",
            label: "Seed",
            name: "seed",
            defaultValue: 0,
            min: 0,
            max: 100,
            step: 1,
            supportsSpline: true,
          },
        ],
      },
    ],
  },
};
