import { OldFilmFilter } from "pixi-filters";
import type { TransformationDefinition } from "../types";
import { filterHandler } from "../filterHandler";

export const oldFilmFilterDefinition: TransformationDefinition = {
  type: "filter",
  compatibleClips: "visual",
  filterName: "OldFilmFilter",
  FilterClass: OldFilmFilter,
  label: "Old Film",
  handler: filterHandler,
  uiConfig: {
    groups: [
      {
        id: "oldfilm_color",
        title: "Color",
        columns: 1,
        controls: [
          {
            type: "slider",
            label: "Sepia",
            name: "sepia",
            defaultValue: 0.3,
            min: 0,
            max: 1,
            step: 0.01,
            supportsSpline: true,
          },
        ],
      },
      {
        id: "oldfilm_noise",
        title: "Noise",
        columns: 1,
        controls: [
          {
            type: "slider",
            label: "Noise",
            name: "noise",
            defaultValue: 0.3,
            min: 0,
            max: 1,
            step: 0.01,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Noise Size",
            name: "noiseSize",
            defaultValue: 1,
            min: 0,
            max: 10,
            step: 0.1,
            supportsSpline: true,
          },
        ],
      },
      {
        id: "oldfilm_scratch",
        title: "Scratches",
        columns: 1,
        controls: [
          {
            type: "slider",
            label: "Scratch",
            name: "scratch",
            defaultValue: 0.5,
            min: 0,
            max: 1,
            step: 0.01,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Scratch Density",
            name: "scratchDensity",
            defaultValue: 0.3,
            min: 0,
            max: 1,
            step: 0.01,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Scratch Width",
            name: "scratchWidth",
            defaultValue: 1,
            min: 0,
            max: 10,
            step: 0.1,
            supportsSpline: true,
          },
        ],
      },
      {
        id: "oldfilm_vignette",
        title: "Vignette",
        columns: 1,
        controls: [
          {
            type: "slider",
            label: "Vignette",
            name: "vignetting",
            defaultValue: 0.3,
            min: 0,
            max: 1,
            step: 0.01,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Vignette Alpha",
            name: "vignettingAlpha",
            defaultValue: 1,
            min: 0,
            max: 1,
            step: 0.01,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Vignette Blur",
            name: "vignettingBlur",
            defaultValue: 1,
            min: 0,
            max: 2,
            step: 0.01,
            supportsSpline: true,
          },
          {
            type: "number",
            label: "Seed",
            name: "seed",
            defaultValue: 0,
            min: 0,
            max: 100,
            step: 1,
            supportsSpline: true,
          },
        ],
      },
    ],
  },
};
