import { ShockwaveFilter } from "pixi-filters";
import type { TransformationDefinition } from "../types";
import { filterHandler } from "../filterHandler";

export const shockwaveFilterDefinition: TransformationDefinition = {
  type: "filter",
  compatibleClips: "visual",
  filterName: "ShockwaveFilter",
  FilterClass: ShockwaveFilter,
  label: "Shockwave",
  handler: filterHandler,
  filterParameterScale: {
    speed: "worldUniform",
    amplitude: "worldUniform",
    wavelength: "worldUniform",
    radius: "worldUniform",
  },
  filterParameterPoints: [{ x: "centerX", y: "centerY", space: "inputLocal" }],
  uiConfig: {
    groups: [
      {
        id: "shockwave_settings",
        title: "Settings",
        columns: 1,
        controls: [
          {
            type: "slider",
            label: "Speed",
            name: "speed",
            defaultValue: 500,
            min: 0,
            max: 2000,
            step: 10,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Amplitude",
            name: "amplitude",
            defaultValue: 30,
            min: 0,
            max: 100,
            step: 1,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Wavelength",
            name: "wavelength",
            defaultValue: 160,
            min: 1,
            max: 500,
            step: 1,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Brightness",
            name: "brightness",
            defaultValue: 1,
            min: 0,
            max: 2,
            step: 0.01,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Radius",
            name: "radius",
            defaultValue: -1,
            min: -1,
            max: 1000,
            step: 1,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Time",
            name: "time",
            defaultValue: 0,
            min: 0,
            max: 10,
            step: 0.01,
            supportsSpline: true,
          },
        ],
      },
      {
        id: "shockwave_center",
        title: "Center",
        columns: 1,
        controls: [
          {
            type: "slider",
            label: "Center X",
            name: "centerX",
            defaultValue: 0.5,
            min: 0,
            max: 1,
            step: 0.01,
            supportsSpline: true,
          },
          {
            type: "slider",
            label: "Center Y",
            name: "centerY",
            defaultValue: 0.5,
            min: 0,
            max: 1,
            step: 0.01,
            supportsSpline: true,
          },
        ],
      },
    ],
  },
};
