// The timeline UI surface (Timeline component, DnD overlay, UI-only overlay
// hooks) lives in `./ui` so API/primitive consumers don't transitively import
// the timeline UI cycle. Only the editor/app shell imports `./ui`.
export {
  countSam2MaskAssetConsumers,
  countBrushMaskAssetConsumers,
  selectResolvedMaskBooleanExpressionForParent,
} from "./useTimelineStore";
export {
  TRACK_HEIGHT,
  CLIP_HEIGHT,
  TRACK_HEADER_WIDTH,
  RULER_HEIGHT,
  EPSILON,
  LEFT_WALL_ID,
  SPLIT_THRESHOLD_PX,
  SNAP_THRESHOLD_PX,
  TICKS_PER_SECOND,
  ADJUSTMENT_DEFAULT_DURATION_TICKS,
  PIXELS_PER_SECOND,
  TICKS_PER_PIXEL,
  MIN_ZOOM,
  MAX_ZOOM,
} from "./constants";
export {
  ticksPerFrame,
  frameToTick,
  tickToFrame,
  snapTickToFrameGrid,
  snapTickToGrid,
  frameIndexFromTick,
  tickFromFrameIndex,
  FRAME_INDEX_EPSILON,
} from "../../core/time/frameGrid";
export type { FrameSnapMode } from "../../core/time/frameGrid";
export {
  pixelsPerSecond,
  ticksPerPixel,
  ticksToPx,
  pxToTicks,
} from "../../core/time/pixelGrid";
export { timelineSpanStyleX } from "./utils/timelineGeometry";
export type { TimelineSpanStyleOptions } from "./utils/timelineGeometry";
export {
  createEndpointOverlayItem,
  createSourceTimeOverlayItem,
} from "./clipOverlayApi";
export type {
  TimelineClipOverlayDefinition,
  TimelineClipOverlayDragContext,
  TimelineClipOverlayItem,
  TimelineClipOverlayRenderContext,
  TimelineClipOverlaySourceProps,
  TimelineClipOverlayVisibility,
} from "./clipOverlayApi";
export {
  insertAssetAtTime,
  insertBaseClipAtTime,
} from "./utils/insertAssetToTimeline";
export { createClipFromAsset } from "./utils/clipFactory";
export {
  CollisionType,
  getCollisionType,
  getMinimumClipDurationTicks,
  getResizeConstraints,
  hasAnyCollision,
  resolveCollision,
} from "./utils/collision";
export {
  getTimelineClips,
  getTimelineStoreForTrustedHostAccess,
  getTimelineModelState,
  getTimelineClipById,
  getTimelineTracks,
  getTimelineTransitions,
  getPrimaryActiveClip,
  getTimelineClipsForTrack,
  getMaskClipsForParent,
  getTimelineDuration,
  getTimelineClipCountForAsset,
  getSelectedTimelineClipIds,
  getSelectedTimelineClipId,
  getSelectedTimelineTransitionId,
  createEmptyTimelineSnapshot,
  getTimelineSnapshot,
  getTimelinePresentationContext,
  getTimelineClipsInPresentationRange,
  getTimelineCompositeContent,
  getTimelineCompositePlacementIds,
  getTimelineMaskClipById,
  getTimelineMaskClipForParent,
  getTimelineBrushMaskClipIds,
  getTimelineBrushMaskAssetConsumerCount,
  getTimelineSam2MaskAssetConsumerCount,
  getExtensionTimelineEntities,
  commitExtensionTimelineTransaction,
  replaceTimelineSnapshot,
  setTimelinePersistenceSuspended,
  addTimelineClip,
  createTimelineClipFromAsset,
  insertTimelineBaseClipAtTime,
  insertTimelineAssetAtTime,
  addTimelineClipsOnNewTracksBelow,
  groupTimelineClipsIntoComposite,
  syncTimelineCompositePlacementRevision,
  remapTimelineCompositePlacement,
  removeTimelineClip,
  removeTimelineClips,
  moveTimelineClips,
  removeTimelineClipsByAssetId,
  replaceTimelineClipAsset,
  toggleTimelineClipMute,
  updateTimelineClipShape,
  updateTimelineTextClipData,
  addTimelineClipTransform,
  updateTimelineClipTransform,
  setTimelineClipTransforms,
  setTimelineClipTransformsAndShape,
  setTimelineClipMaskCompositeTransforms,
  removeTimelineClipTransform,
  addTimelineAdjustmentClip,
  setTimelineAdjustmentDepth,
  setTimelineAdjustmentRetimingMode,
  selectTimelineClip,
  clearTimelineClipSelection,
  selectTimelineTransition,
  addTimelineTransition,
  updateTimelineTransitionParameters,
  addTimelineClipMask,
  duplicateTimelineClipMask,
  updateTimelineClipMask,
  removeTimelineClipMask,
  setTimelineClipMaskBooleanExpression,
  setTimelineClipMaskCompositionAlgebra,
  setTimelineClipMaskExpressionEnabled,
  addTimelineClipComponent,
  updateTimelineClipComponent,
  removeTimelineClipComponent,
  flushPendingTimelinePersistence,
  selectTimelineClipById,
  selectPrimaryActiveClip,
  selectMaskClipsForParent,
  selectTimelineClipsForTrack,
  selectTimelineDuration,
  selectTimelineClipCountForAsset,
  parseMaskClipId,
  useTimelineClip,
  usePrimaryActiveClip,
  useTimelineClips,
  useTimelineTracks,
  useSelectedTimelineClipIds,
  useSelectedTimelineClipId,
  useTimelineClipsForTrack,
  useMaskClipsForParent,
  useTimelineDuration,
  useTimelineClipCountForAsset,
  useTimelineModelState,
  useTimelineTransitions,
  useSelectedTimelineTransitionId,
} from "./api";
export type {
  AddTimelineClipsOnNewTracksEntry,
  ExtensionTimelineCommand,
  TimelineStoreState,
  UpdateTimelineClipComponentFn,
  UpdateTimelineClipTransformPayload,
} from "./api";
