export {
  DuplicateExtensionContributionError,
  ExtensionContributionRegistry,
  InvalidExtensionContributionIdError,
} from "./registry/ExtensionContributionRegistry";
export { ExtensionApprovalGate } from "./components/ExtensionApprovalGate";
export { ExtensionManagerDialog } from "./components/ExtensionManagerDialog";
export { FrontendExtensionBootstrap } from "./components/FrontendExtensionBootstrap";
export { installExtensionMenuContributions } from "./menus/menuContributionsInstall";
export { VLO_EXTENSION_SDK_VERSION } from "./constants";
export { ingestExtensionAsset } from "./assets/publicApi";
export {
  extensionPayloadSchema,
  jsonValueSchema,
} from "./persistence/extensionPayload";
export {
  collectProjectExtensionRequirements,
  getExtensionPayloadProviderId,
} from "./persistence/extensionRequirements";
export {
  ExtensionPayloadProviderRegistry,
  extensionPayloadProviderRegistry,
} from "./persistence/ExtensionPayloadProviderRegistry";
export {
  ExtensionEntityProviderRegistry,
  extensionEntityProviderRegistry,
} from "./entities/ExtensionEntityProviderRegistry";
export type {
  ExtensionPayloadAssetReferenceResolution,
  ExtensionPayloadResolution,
} from "./persistence/ExtensionPayloadProviderRegistry";
export type {
  ExtensionProviderAvailability,
  ExtensionProviderAvailabilityResolver,
  ExtensionRequirementSource,
  ProjectExtensionRequirement,
} from "./persistence/extensionRequirements";
export type {
  BoundExtensionContributionRegistry,
  ExtensionContributionDefinition,
  ExtensionContributionRegistration,
  RegisteredExtensionContribution,
} from "./registry/ExtensionContributionRegistry";
export {
  ExtensionActivationError,
  ExtensionActivationCancelledError,
  ExtensionActivationTimeoutError,
  ExtensionDeactivationError,
  ExtensionHost,
  ExtensionLifecycleStateError,
  ExtensionRegistrationClosedError,
  InvalidExtensionIdentityError,
  InvalidExtensionResourceError,
} from "./ExtensionHost";
export type { ExtensionHostOptions } from "./ExtensionHost";
export type {
  ExtensionInventoryItem,
  ExtensionInventoryStatus,
} from "./services/extensionManagementApi";
export type {
  ExtensionAnimationApi,
  ExtensionAnimationDataMigration,
  ExtensionAnimationEditorDomain,
  ExtensionCompiledInterpolationSegment,
  ExtensionCompiledScalarSource,
  ExtensionCompiledSpatialPath,
  ExtensionInterpolationApi,
  ExtensionInterpolationCompileInput,
  ExtensionInterpolationDefinition,
  ExtensionInterpolationEditorProps,
  ExtensionInterpolationRegistration,
  ExtensionKeyframedScalarParameter,
  ExtensionPoint2D,
  ExtensionScalarKeyframe,
  ExtensionScalarRemap,
  ExtensionScalarSampleContext,
  ExtensionScalarSourceApi,
  ExtensionScalarSourceDefinition,
  ExtensionScalarSourceEditorProps,
  ExtensionScalarSourceParameter,
  ExtensionScalarSourceRegistration,
  ExtensionScalarTimeMap,
  ExtensionScalarValue,
  ExtensionSpatialPathApi,
  ExtensionSpatialPathBounds,
  ExtensionSpatialPathDefinition,
  ExtensionSpatialPathEditorProps,
  ExtensionSpatialPathOverlayContext,
  ExtensionSpatialPathOverlayParameters,
  ExtensionSpatialPathParameter,
  ExtensionSpatialPathRegistration,
  ExtensionTrustedSpatialPathOverlayInstance,
} from "./types";
export type {
  ExtensionAssetApi,
  ExtensionAssetIngestInput,
  ExtensionBackendApi,
  ExtensionBackendArtifact,
  ExtensionBackendArtifactUploadOptions,
  ExtensionBackendJobDiagnostic,
  ExtensionBackendJobReadiness,
  ExtensionBackendJobSnapshot,
  ExtensionBackendJobStatus,
  ExtensionBackendJobType,
  ExtensionBackendJobWaitOptions,
  ExtensionSourceDimensions,
  ExtensionTimelineClipSnapshot,
  ExtensionTimelineMaskActiveRange,
  ExtensionTimelineMaskBounds,
  ExtensionTimelineMaskSnapshot,
  ExtensionTimelineProjectSnapshot,
  ExtensionTimelineTransitionCreateInput,
  ExtensionTimelineTransitionSnapshot,
  ExtensionTimelineTransformInput,
  ExtensionTimelineTransformSnapshot,
} from "./types";
export type {
  ExtensionTransitionApi,
  ExtensionTransitionCheckboxControl,
  ExtensionTransitionColorLayer,
  ExtensionTransitionControl,
  ExtensionTransitionControlGroup,
  ExtensionTransitionDefinition,
  ExtensionTransitionFrame,
  ExtensionTransitionNumberControl,
  ExtensionTransitionParameterMigration,
  ExtensionTransitionRegistration,
  ExtensionTransitionRenderInput,
  ExtensionTransitionSelectControl,
  ExtensionTransitionSelectOption,
  ExtensionTransitionTextControl,
  ExtensionTransitionTransform,
  ExtensionTransitionZOrder,
} from "./types";
export { ExtensionBackendApiError } from "./backend/createExtensionBackendApi";
export type {
  ExtensionActivationState,
  ExtensionActivationStatus,
  ExtensionApiFactory,
  ExtensionApiScope,
  ExtensionCleanup,
  ExtensionCatalogueApi,
  ExtensionCatalogueInfo,
  ExtensionCatalogueOptionContribution,
  ExtensionCatalogueOptionView,
  ExtensionCanvasPointerEvent,
  ExtensionCanvasToolApi,
  ExtensionCanvasToolDefinition,
  ExtensionCanvasToolRegistration,
  ExtensionCanvasToolSession,
  ExtensionClipOverlayItem,
  ExtensionClipOverlayItemDrag,
  ExtensionContext,
  ExtensionDiagnostic,
  ExtensionDiagnosticLevel,
  ExtensionDiagnosticPhase,
  ExtensionDisposable,
  ExtensionEntityAssetSnapshot,
  ExtensionEntityProviderApi,
  ExtensionEntityProviderRegistration,
  ExtensionEntityInspectorProps,
  ExtensionEntityRenderContext,
  ExtensionEntityRenderParameters,
  ExtensionGenerationApi,
  ExtensionGenerationInputSnapshot,
  ExtensionGenerationTransaction,
  ExtensionGenerationTransactionResult,
  ExtensionDeclarativeHostFilter,
  ExtensionExecutionMode,
  ExtensionIdentity,
  ExtensionLifecycleResult,
  ExtensionLogger,
  ExtensionMenuApi,
  ExtensionMenuCommandContribution,
  ExtensionMenuCondition,
  ExtensionMenuInfo,
  ExtensionMuiRuntime,
  ExtensionModule,
  ExtensionPayload,
  ExtensionPayloadMigration,
  ExtensionPayloadProviderApi,
  ExtensionPayloadProviderDefinition,
  ExtensionPayloadProviderRegistration,
  ExtensionPanelUiRuntime,
  ExtensionResource,
  ExtensionTimelineApi,
  ExtensionTimelineCoalescingOptions,
  ExtensionTimelineMaskCreateInput,
  ExtensionTimelineTransactionOptions,
  ExtensionTimelineEntityCreateInput,
  ExtensionTimelineEntitySnapshot,
  ExtensionTimelineTransaction,
  ExtensionTimelineTransactionFailureCode,
  ExtensionTimelineTransactionResult,
  ExtensionHostFilter,
  ExtensionHostFilterTransformationDefinition,
  ExtensionHostRuntimeApi,
  ExtensionPixiFilterOptions,
  ExtensionPixiRuntime,
  ExtensionReactRuntime,
  ExtensionTransformationApi,
  ExtensionTransformationCheckboxControl,
  ExtensionTransformationControl,
  ExtensionTransformationControlGroup,
  ExtensionTransformationDefinition,
  ExtensionTransformationNumberControl,
  ExtensionTransformationRegistration,
  ExtensionTransformationSelectControl,
  ExtensionTransformationSelectOption,
  ExtensionTransformationTextControl,
  ExtensionTrustedFilterApplyContext,
  ExtensionTrustedApi,
  ExtensionTrustedHostApi,
  ExtensionTrustedHostEntry,
  ExtensionTrustedFilterInstance,
  ExtensionTrustedFilterTransformationDefinition,
  ExtensionTrustedEntityProviderDefinition,
  ExtensionTrustedEntityRenderableInstance,
  ExtensionTrustedPixiObjectInstance,
  ExtensionTrustedTransformationApplyContext,
  ExtensionTrustedTransformationDefinition,
  ExtensionTrustedTransformationState,
  ExtensionTrustedUiComponentDefinition,
  ExtensionTrustedUiModalDefinition,
  ExtensionTrustedUiViewDefinition,
  ExtensionUiApi,
  ExtensionUiComponentProps,
  ExtensionUiModalComponentProps,
  ExtensionUiModalSize,
  ExtensionUiNoticeDefinition,
  ExtensionUiNoticeTone,
  ExtensionUiRegistration,
  ExtensionUiSlotId,
  ExtensionUiViewComponentProps,
  ExtensionUiViewRegion,
  JsonValue,
  VloExtensionApi,
} from "./types";
