"""Compatibility exports for the supported extension backend-job surface."""

from services.jobs.manager import (
    DEFAULT_FINISHED_JOB_TTL_SECONDS,
    DEFAULT_JOB_TIMEOUT_SECONDS,
    DEFAULT_JOB_VALIDATION_TIMEOUT_SECONDS,
    DEFAULT_MAX_JOB_DIAGNOSTICS,
    DEFAULT_MAX_JOBS_PER_EXTENSION,
    DEFAULT_MAX_UNCLAIMED_ARTIFACTS_PER_EXTENSION,
    DEFAULT_UNCLAIMED_ARTIFACT_TTL_SECONDS,
    BackendJobArtifactAccess,
    BackendJobCancelledError,
    BackendJobCapacityError,
    BackendJobContext,
    BackendJobDefinition,
    BackendJobDiagnostic,
    BackendJobDiagnosticLevel,
    BackendJobError,
    BackendJobIdentity,
    BackendJobManager,
    BackendJobNotFoundError,
    BackendJobNotReadyError,
    BackendJobReadiness,
    BackendJobSnapshot,
    BackendJobStatus,
    BackendJobValidationError,
)

__all__ = [
    "DEFAULT_FINISHED_JOB_TTL_SECONDS",
    "DEFAULT_JOB_TIMEOUT_SECONDS",
    "DEFAULT_JOB_VALIDATION_TIMEOUT_SECONDS",
    "DEFAULT_MAX_JOB_DIAGNOSTICS",
    "DEFAULT_MAX_JOBS_PER_EXTENSION",
    "DEFAULT_MAX_UNCLAIMED_ARTIFACTS_PER_EXTENSION",
    "DEFAULT_UNCLAIMED_ARTIFACT_TTL_SECONDS",
    "BackendJobArtifactAccess",
    "BackendJobCancelledError",
    "BackendJobCapacityError",
    "BackendJobContext",
    "BackendJobDefinition",
    "BackendJobDiagnostic",
    "BackendJobDiagnosticLevel",
    "BackendJobError",
    "BackendJobIdentity",
    "BackendJobManager",
    "BackendJobNotFoundError",
    "BackendJobNotReadyError",
    "BackendJobReadiness",
    "BackendJobSnapshot",
    "BackendJobStatus",
    "BackendJobValidationError",
]
